import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load("model.pkl")

# Page settings
st.set_page_config(
    page_title="Diabetes Risk Prediction",
    page_icon="🩺"
)

st.title("🩺 Diabetes Risk Prediction")
st.write("Enter patient information to predict diabetes risk.")

st.info(
    "⚠️ This tool is for educational/research purposes only "
    "and is not a medical diagnosis."
)

st.header("Patient Information")

Age = st.number_input("Age", 0.0, 100.0, 40.0)

Gender = st.selectbox("Gender", [0, 1])

Rgn = st.selectbox("Region (Rgn)", [0, 1])

wt = st.number_input("Weight (kg)", 0.0, 200.0, 70.0)

BMI = st.number_input("BMI", 0.0, 300.0, 25.0)

wst = st.number_input("Waist", 0.0, 150.0, 40.0)

sys = st.number_input("Systolic Blood Pressure", 0, 300, 120)

dia = st.number_input("Diastolic Blood Pressure", 0, 200, 80)

his = st.selectbox("History of Diabetes", [0, 1])

A1c = st.number_input("HbA1c", 0.0, 20.0, 5.5)

BSR = st.number_input("Blood Sugar Random (B.S.R)", 0, 600, 120)

vision = st.selectbox("Vision Problem", [0, 1])

Exr = st.number_input("Exercise", 0, 300, 30)

dipsia = st.selectbox("Excessive Thirst", [0, 1])

uria = st.selectbox("Excessive Urination", [0, 1])

Dur = st.number_input("Duration", 0.0, 50.0, 0.0)

neph = st.selectbox("Kidney Problem", [0, 1])

HDL = st.number_input("HDL", 0, 100, 50)


# Prediction
if st.button("🔍 Predict Diabetes Risk"):

    patient = pd.DataFrame([[
        Age,
        Gender,
        Rgn,
        wt,
        BMI,
        wst,
        sys,
        dia,
        his,
        A1c,
        BSR,
        vision,
        Exr,
        dipsia,
        uria,
        Dur,
        neph,
        HDL
    ]], columns=[
        "Age",
        "Gender",
        "Rgn ",
        "wt",
        "BMI",
        "wst",
        "sys",
        "dia",
        "his",
        "A1c",
        "B.S.R",
        "vision",
        "Exr",
        "dipsia",
        "uria",
        "Dur",
        "neph",
        "HDL"
    ])

    prediction = model.predict(patient)[0]
    probability = model.predict_proba(patient)[0]

    confidence = probability[prediction] * 100

    st.subheader("Prediction Result")

    if prediction == 1:
        st.error("🔴 High Risk")
    else:
        st.success("🟢 Low Risk")

    st.write(f"**Model Probability: {confidence:.2f}%**")

    st.warning(
        "This prediction is generated by a machine learning model "
        "and should not be considered a medical diagnosis."
    )
